### ISSUE TITLE
Fallout 4 modlists that generate custom BSAs crash

### ISSUE THREAD

**Issue by Niedzwiedzw** [Ryan-rsm-McKenzie/bsa-rs#13]
Yeah so we have a small success, I have tested several skyrim modlists and they all work flawlessly 🎉.
The fallout 4 modlists crash on launch though and I have no idea why. Do you have any idea how I could debug this?

here's the code for current iteration, maybe you could take a look
https://github.com/Niedzwiedzw/hoolamike/blob/feature/fixing-fallout4-archive/crates/hoolamike/src/install_modlist/directives/create_bsa/fallout_4.rs

EDIT: I have posted the wrong branch before

**Comment by Ryan-rsm-McKenzie** [comment]
Is there a reason you can't check the [archive hashes](https://github.com/Niedzwiedzw/hoolamike/blob/2d27bfcdf0670e364f767e75d50c75c9bffcdfae/crates/hoolamike/src/install_modlist/directives/create_bsa/fallout_4.rs#L151) match the directive? The resulting archive should at least be the same length, even if the hash doesn't match.

**Comment by Niedzwiedzw** [comment]
I assummed they will never match because of BTreeMap ordering?

**Comment by Niedzwiedzw** [comment]
also, wabbajack uses Welch filter to resize their textures which is not available to us

**Comment by Ryan-rsm-McKenzie** [comment]
Try using a crash logger for fo4 and post the log.

**Comment by Niedzwiedzw** [comment]
https://pastebin.com/hCVCRrvk

nothing interesting here I'm afraid

**Comment by Ryan-rsm-McKenzie** [comment]
Try generating the same mod pack using wabbajack, and then swap the archives you generate into the wabbajack mod list until it crashes.

**Comment by Niedzwiedzw** [comment]
there is no way to use the welch filter with dirextxtex right?

**Comment by Niedzwiedzw** [comment]
here is how they do it https://github.com/wabbajack-tools/wabbajack/blob/e8eff20b6558e791f15bc24a5db1957134669639/Wabbajack.Hashing.PHash/CrossPlatformImageLoader.cs#L92

**Comment by Niedzwiedzw** [comment]
```toml
[Fixes]
ActorIsHostileToActor = true           # Fixes a crash when invoking Actor.IsHostileToActor with a none form
BackportedBA2Support = true            # Adds support for the new BA2 archive format introduced in NG update 1.10.980 to VR.
BGSAIWorldLocationRefRadiusNull = true # Fixes a crash with BGSAIWorldLocationRefRadius when the target ref is null
BSLightingShaderMaterialGlowmap = true # Fixes a crash with a bad BSLightingShaderMaterialGlowmap
CellInit = true                        # Fixes a crash where a form does not get converted to a form pointer on unloaded cells
CreateD3DAndSwapChain = true           # Fixes a crash on startup when enumerating certain monitor display modes
EncounterZoneReset = true              # Fixes encounter zones resetting immediately once you leave them on foot
GreyMovies = true                      # Fixes a bug where movies that don't define "BackgroundAlpha" on their movie root could load with a grey background
InteriorNavCut = true                  # Fixes the engine bug that causes workshop navmesh cuts to persist throughout all interior cells. https://simsettlements.com/site/index.php?threads/major-new-fallout-4-bug-discovered-shared-interior-cell-navcutting.26755/
FixScriptPageAllocation = true         # Fix unintentionally allocating script pages when getting largest available page, but out of memory.
FixToggleScriptsCommand = true         # Fixes ToggleScripts command not persisting when saving/stack dumping. Scripts will now stay turned off when toggled off, and on when toggled on.
MagicEffectApplyEvent = true           # Fixes a crash when magic effect apply events are dispatched on null references
MovementPlanner = true                 # Fixes a bug where the the movement planner crashes with non-actors
PackageAllocateLocation = true         # Fixes a crash when allocating the location for a package
SafeExit = true                        # Fixes crashes related to exiting the game that can be caused erroneously by F4SE plugin hooks
TESObjectREFRGetEncounterZone = true   # Fixes a crash when looking up the encounter zone on a reference that has not yet initialized
UnalignedLoad = true                   # Fixes a crash related to SIMD intrinsics with an aligned move on unaligned memory
UtilityShader = true                   # Fixes a crash when a shader can't be found for a given technique id
WorkBenchSwap = true                   # Fixes a crash where you are scrapping or swapping many inventory items in the workbench
PipboyLightInvFix = true               # Fixes a crash when you have the pipboy light on and checking inventory

[Patches]
Achievements = false            # Enables achievements on modded saves
BSMTAManager = true               # General rendering performance improvement
BSPreCulledObjects = true         # General rendering performance improvement
BSTextureStreamerLocalHeap = false # Replaces the texture streamer's local heap with os allocators
HavokMemorySystem = false         # Replaces the havok memory system with os allocators
INISettingCollection = true       # Massively improves startup times for large load orders by optimizing ini setting loading
InputSwitch = false               # Automatically swaps inputs between kb+m/controller
MaxStdIO = 2048                   # Replaces the maximum stdio handles. Default 512, max 8192 https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170
MemoryManager = false              # Replaces the global memory manager with os allocators
MemoryManagerDebug = false       # Enables debug tracing to determine faulting modules
ScaleformAllocator = false         # Replaces the scaleform memory allocator with os allocators
SmallBlockAllocator = false        # Replaces the small block memory allocators with os allocators
WorkshopMenu = true               # Alleviates lag while opening the workshop menu

[Tweaks]
# Maximum papyrus operations per frame. Higher number means better script performance on average
# Has a very minor impact on framerate, and varies from script to script. (Default: 500, Vanilla value: 100). Recommended Range: 100-2000.
MaxPapyrusOpsPerFrame = 2000

[Warnings]
CreateTexture2D = true   # Warns when a call to CreateTexture2D fails
ImageSpaceAdapter = true # Warns on bad IMAD definitions which will corrupt your memory and crash your game

[Compatibility]
F4EE = true # 1.6.20 - Patches various LooksMenu bugs

[Debug]
#Symcache = "c:\symcache"	# Location of Symcache.
#WaitForDebugger = false 	# Whether to wait for debugger to attach when a crash occurs
```

could I edit something here? I noticed that Buffout4 is already included in the modlist I'm testing (`Wasteland Reborn`) and that you're the author of Buffout4 so I figured I'd ask here
